### ISSUE TITLE
Under heavy load the LRUCache can fail to retrieve image metadata

### ISSUE THREAD

**Issue by deanmarcussen** [SixLabors/ImageSharp.Web#140]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp.Web
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp.Web/issues) and [closed](https://github.com/SixLabors/ImageSharp.Web/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Under heavy load the LRUCache may return what seems to be an empty `ImageCacheMetadata` (when I say empty, it is not null, but has no apparent values).

This results in a dictionary error when trying to read the format utilities in `PhysicalFileSystemCacheResolver`
```
               string path = Path.ChangeExtension(
                this.metaFileInfo.PhysicalPath,
                this.formatUtilities.GetExtensionFromContentType(this.metadata.ContentType));
```

### Steps to Reproduce

```
deanmarcussen@dean ImageSharp.Web % ~/Scripts/bombardier -c 100 -d 5s -k "http://localhost:2646/imagesharp-logo.png?width=300"
Bombarding http://localhost:2646/imagesharp-logo.png?width=300 for 5s using 100 connection(s)
[=============================================================================================================================================================================] 5s
Done!
Statistics        Avg      Stdev        Max
  Reqs/sec      3314.89    1101.36    5268.09
  Latency       30.18ms    22.94ms   468.19ms
  HTTP codes:
    1xx - 0, 2xx - 16654, 3xx - 0, 4xx - 0, 5xx - 7
    others - 0
  Throughput:    18.61MB/s
```

On this run 7 500 errors, corresponding to this exception
```
2021-02-26 08:09:33.2911|1|ERROR|Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware|An unhandled exception has occurred while executing the request. System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at SixLabors.ImageSharp.Web.Resolvers.PhysicalFileSystemCacheResolver.OpenReadAsync() in /Users/deanmarcussen/Projects/ImageSharp.Web/src/ImageSharp.Web/Caching/PhysicalFileSystemCacheResolver.cs:line 44
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.SendResponseAsync(ImageContext imageContext, 

... truncated for brevity.
```

I can so far trace this back to 
```
                            // Now resolve the cached image metadata storing the result.
                            ImageCacheMetadata cachedImageMetadata = await cachedImageResolver.GetMetaDataAsync();
                            // ImageCacheMetadata cachedImageMetadata = await
                            //     CacheMetadataLru.GetOrAddAsync(
                            //         key,
                            //         _ => cachedImageResolver.GetMetaDataAsync());
```

where removing the LRU cache resolves the issue (and obviously goes a lot slower!)

Have not had time yet to dig into what's going on with the LRU cache, i.e. where the `GetOrAddAsync` might be going wrong.

But from initial look, it might be the issue where `GetOrAdd` is not thread safe, and there's a race going on.

This is why `Lazy` was used in the other implementation for the `Workers` though I've since read there might be better alternatives.

Where did the LRU implementation come from? 
Any chance it's been updated since? 

### System Configuration

Current repro is on macos, core3, latest pull from with the sample project, but also reported on gitter w / OrchardCore in production on IIS Windows Server 2016.

**Comment by JimBobSquarePants** [comment]
I read that as 7500 errors! Got a proper fright! 

I do recall seeing small error counts when we did the original throughput tests but we decided to leave them for the moment. 

The implementation I based the code on is here. I'll definitely need help solving this one as I don't have the tooling you do.

https://github.com/bitfaster/BitFaster.Caching

**Comment by deanmarcussen** [comment]
Don't panic, only 7!

Looks to me like the valuefactories are running twice sometimes (which is what it does), on `GetOrAdd`, and the `IImageMetadata` returned is not always the same `IImageMetadata` that is held on the `PhysicalFileSystemCacheResolver` which is causing it to get confused. 

Or there are multiple calls to `GetMetadataAsync` which is resetting the value during the run (too many threads hitting the same thing) 

When this happens the `PhysicalFileSystemCacheResolver` has no `IImageMetadata` associated with it, so it bombs.

Is there a reason why it's a struct? 

I turned it into a class to make checking references easier, which is where I think the multiple executions are coming in.

Need to understand why there is
`CacheResolverLru`

and 

`CacheMetadataLru`

and why they are not just resolved in the same cycle.

It seems to resolve (and hasn't had an impact on performance) by resolving them together
```
                            IImageCacheResolver cachedImageResolver = await
                                CacheResolverLru.GetOrAddAsync(
                                    key,
                                    async k => 
                                    {
                                        var resolver = await this.cache.GetAsync(k);
                                        if (resolver != null)
                                        {
                                            await resolver.GetMetaDataAsync();
                                        }
                                        return resolver;
                                    });
```

**Comment by brianpopow** [comment]
> Don't panic, only 7!
> 

I was also reading 7500 errors 😄 

I was able to reproduce the issue with `bombardier`, but it took much more requests to trigger.

```
bombardier -c 100 -d 500s -k "http://localhost:2646/imagesharp-logo.png?width=300"
Bombarding http://localhost:2646/imagesharp-logo.png?width=300 for 8m20s using 100 connection(s)
[=================================================================================================================================================================================================================] 8m20s Done!
Statistics        Avg      Stdev        Max
  Reqs/sec     37575.73    4774.26   59895.57
  Latency        2.64ms   296.36us   475.56ms
  HTTP codes:
    1xx - 0, 2xx - 18793280, 3xx - 0, 4xx - 0, 5xx - 8
    others - 0
  Throughput:   179.81MB/s
```

**Comment by JimBobSquarePants** [comment]
> I was able to reproduce the issue with bombardier, but it took much more requests to trigger.

Someone needs to provide me with a file I can click to run this.

@deanmarcussen 

The reason there are two separate caches is because `await resolver.GetMetaDataAsync();` returns a new instance each time and I wasn't smart enough to simply do a null check.. 

However, I cannot see why we cannot simplify things to the following:

```c#
// Get the source metadata for processing, storing the result for future checks.
ImageMetadata sourceImageMetadata = await
    SourceMetadataLru.GetOrAddAsync(
        key,
        _ => sourceImageResolver.GetMetaDataAsync());

// Attempt to resolve the cached image metadata storing the result.
// If not found, we return early. No further checks necessary.
ImageCacheMetadata cachedImageMetadata = await
    CacheMetadataLru.GetOrAddAsync(
        key,
        async k =>
        {
            IImageCacheResolver resolver = await this.cache.GetAsync(k);
            if (resolver != null)
            {
                return await resolver.GetMetaDataAsync();
            }

            return default;
        });

// Has the image ever been cached?
// Has the cached image expired?
// Or has the source image changed since the image was last cached?
if (cachedImageMetadata == default
    || cachedImageMetadata.ContentLength == 0 // Fix for old cache without length property
    || cachedImageMetadata.CacheLastWriteTimeUtc <= (DateTimeOffset.UtcNow - this.options.CacheMaxAge)
    || cachedImageMetadata.SourceLastWriteTimeUtc != sourceImageMetadata.LastWriteTimeUtc)
{
    // We want to remove the metadata from the store so that the next check gets the updated file.
    CacheMetadataLru.TryRemove(key);
    return (true, sourceImageMetadata);
}
```

The reason `ImageCacheMetadata` is a struct is simply to keep allocations down.

**Comment by brianpopow** [comment]
> Someone needs to provide me with a file I can click to run this.
> 

You can install `bombardier` via chocolatey. Its seems to be a very useful tool for benchmarking: [bombardier](https://github.com/codesenberg/bombardier)

Then simply run the example project `ImageSharp.Web.Sample` 

And run the following command:

> bombardier -c 100 -d 500s -k "http://localhost:2646/imagesharp-logo.png?width=300"

This will do constant requests to given URL with 100 concurrent connections for 500 seconds. After its done it will print a handy summary.

**Comment by JimBobSquarePants** [comment]
Ooh! Let’s get this added to the docs!

**Comment by deanmarcussen** [comment]
> The reason there are two separate caches is because

Cool, just checking I wasn't missing something crucial ;)

> However, I cannot see why we cannot simplify things to the following:

Yes, I thought about it over lunch and agree, I'll just join them together into one cache.

It's reasonably crucial that the same instance of metadata matches the associated image resolver, or the image resolver can get quite confused, but it's a non trivial change to the interfaces / design etc, so will keep it simple.

I think it'll need to return an image resolver, because it's needed later on, in `SendResponseAsync`

Ultimately the LRU Cache may be better served by being more task based, to prevent the value factories potentially running multiple times, but that being said, the factories are realistically quite low cost operations, so to occasionally run one twice, and discard one of the results, is probably cheaper than the refactor (and cost of await).

**Comment by JimBobSquarePants** [comment]
Ah yes, forgot about the serve part! 

We need to ensure then that refactor does not duplicate `GetMetaDataAsync` calls because they are expensive . (Urgh why is the D capitalised!)
