### ISSUE TITLE
Wrong log level for non-existent files

### ISSUE THREAD

**Issue by sebastienros** [SixLabors/ImageSharp.Web#143]
Related to this log:

https://github.com/SixLabors/ImageSharp.Web/blob/451da152293154bff58c6943b37ca5b26ca9f26b/src/ImageSharp.Web/Middleware/LoggerExtensions.cs#L31

It's using Error level which means whenever a non-existent image is requested there will be a log message. We think (OC) this should be `Information` only.

I don't think we can lower the log level for specific events, and we don't want to discard all errors.

**Comment by JimBobSquarePants** [comment]
Agreed. We should sanitize the entire list against the approach in the [StaticFileMiddleware](https://github.com/dotnet/aspnetcore/blob/e1a984898eb5b209975185020c4b1cb7990bcd50/src/Middleware/StaticFiles/src/LoggerExtensions.cs#L47-L49)

**Comment by sebastienros** [comment]
I am not against Debug, and doing what aspnet does. At least if they are wrong you can blame them. And they probably thought some more time about the right level already.
