### ISSUE TITLE
Missing content root folder triggers an exception

### ISSUE THREAD

**Issue by sebastienros** [SixLabors/ImageSharp.Web#15]
Repro: Delete the `wwwroot` folder, and see this exception

```
ArgumentNullException: Value cannot be null. Parameter name: path1 System.IO.Path.Combine(string path1, string path2) SixLabors.ImageSharp.Web.Caching.PhysicalFileSystemCache+<SetAsync>d__12.MoveNext()
```

Ideally the exception should be more descriptive. Or just be no-op without an exception.

**Comment by JimBobSquarePants** [comment]
Thanks, Where's the exception thrown?

**Comment by sebastienros** [comment]
Direct link https://github.com/SixLabors/ImageSharp.Web/blob/master/src/ImageSharp.Web/Caching/PhysicalFileSystemCache.cs#L135

Apparently the value is null for the first parameter which is `this.environment.WebRootPath`.

Tracked it down in the source: https://github.com/aspnet/Hosting/blob/b187c1adc4db343ad985e3d45cfb4f77180966e6/src/Microsoft.AspNetCore.Hosting/Internal/HostingEnvironmentExtensions.cs#L36

That's super weird to only assign this path if the folder exists. Will talk to the team on Monday and file an issue in necessary.

But I think we still need to do a check here and throw a meaningful exception. We'll do a PR if you don't beat me to it.

**Comment by JimBobSquarePants** [comment]
Oh that is really weird! We can do a meaningful exception certainly but what would you expect a fallback to be if we were to allow deletion? Do we always require a `wwwroot` folder for ASP.NET Core?  I thought we did.

**Comment by sebastienros** [comment]
At least I assume it no-op if the folder doesn't exists, which is what ASP.NET static file provider must be doing. https://github.com/aspnet/StaticFiles/blob/dev/src/Microsoft.AspNetCore.StaticFiles/DefaultFilesMiddleware.cs#L70

**Comment by JimBobSquarePants** [comment]
I think throwing then is best with a meaningful exception message. I don't want someone not checking their logs and missing that they're not caching the images.

**Comment by gtmoraisomd** [comment]
I just created the wwwroot folder there and it was fine.
