### ISSUE TITLE
Response body is sometimes empty when processing multiple identical queries

### ISSUE THREAD

**Issue by markmccaigue** [SixLabors/ImageSharp.Web#158]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp.Web
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp.Web/issues) and [closed](https://github.com/SixLabors/ImageSharp.Web/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I'm brand new to the ImageSharp codebase, so apologies if this is user error.

Some requests seem to be getting responses with a 200 status code, but a ContentLength of 0 and an empty body. It seems this is mostly in cases where the same request is hitting the server a few times around the same sort of time.

### Steps to Reproduce
I've had a go at modifying one of the existing tests to assert the ContentLength is not 0, and it does fail for me, please see below.

AzureBlobStorageCacheServerTests
```
        [Theory]
        [InlineData(TestConstants.PhysicalTestImage)]
        [InlineData(TestConstants.AzureTestImage)]
        public async Task CanProcessMultipleIdenticalQueriesAsync(string url)
        {
            Task[] tasks = Enumerable.Range(0, 100).Select(i => Task.Run(async () =>
            {
                var command = i % 2 == 0 ? Command : Command2;
                using HttpResponseMessage response = await this.HttpClient.GetAsync(url + command);
                Assert.NotNull(response);
                Assert.True(response.IsSuccessStatusCode);
                // I have added this additional assertion below. If I modify the enumerable range to (0, 2), the test passes
                // If I leave the enumerable alone and generate a new width in each iteration, the test eventually passes
                // It seems to be only multiple identical requests which have the issue
                Assert.True(response.Content.Headers.ContentLength > 0);
            })).ToArray();

            var all = Task.WhenAll(tasks);
            await all;
            Assert.True(all.IsCompletedSuccessfully);
        }
```

I have a vague notion that we could be hitting imageContext.SendAsync fewer times than ProcessRequestAsync in the ImageSharpMiddleware, which makes me a little suspicious the issue could lie within some of the static caching in this middleware.

### System Configuration
The test above is failing for me in VS2019 16.9.3.

- ImageSharp.Web version:
Current master branch, but repro'd in 1.0.2 of SixLabors.ImageSharp.Web and SixLabors.ImageSharp.Web.Providers.Azure in a dev environment to prompt the initial investigation
- Environment (Operating system, version and so on):
- Windows 10 Version	10.0.19041 Build 19041
- .NET Framework version:
- Modified test is failing on netcoreapp2.1 and 3.1

**Comment by deanmarcussen** [comment]
Are you able to reproduce the same issue with the Physical file provider tests, or are you just seeing the issue when using the blob client?

**Comment by markmccaigue** [comment]
I've just checked, and if I make the same modification to the CanProcessMultipleIdenticalQueriesAsync test in the PhysicalFileSystemCacheServerTests class (i.e. assert that the Content Length is > 0), I'm seeing that they will also fail, so it looks like the issue is manifested in both scenarios.

**Comment by deanmarcussen** [comment]
Thanks for checking. I can repro.

> I have a vague notion that we could be hitting imageContext.SendAsync

Think you might be onto something there. Looking into it.

**Comment by markmccaigue** [comment]
Not a problem, thanks for checking it out 👍

**Comment by JimBobSquarePants** [comment]
Thanks @deanmarcussen for picking this up!

**Comment by deanmarcussen** [comment]
No trouble, sadly, there's a definite issue with the `ConcurrentDictionary` arrangement.

Where we swapped the `Doorman` async lock, I've not properly taken into account the previous behaviour. 😞 

We swapped it to prevent multiple writes, as it was locking at the entry, and then carrying on afterwards, and resizing and writing the file again (please correct me if I'm wrong, as the `Doorman` wasn't code I knew well )

We've gone too far the other direction now, and are pausing it at entry, but also returning the response in the value factory for the task, so on multiple requests, it's only returning one response, as only one value factory runs.

I've written a quick fix, moving the response out of the value factory, and it's now pausing (non blocking await) on the write, and also returning both responses (and same on reads). 

The 'quick fix' needs a bit more refactoring, to handle stream disposal properly, and then we'll see where we're at with it.

**Comment by markmccaigue** [comment]
That sounds like great progress! I really appreciate you guys looking at this so quickly.
