### ISSUE TITLE
Incorrect CI Version Numbers.

### ISSUE THREAD

**Issue by JimBobSquarePants** [SixLabors/ImageSharp.Web#18]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The nightly versions numbers are not generating the expected value. `1.0.0-ci0010` is currently the latest but is lower than `1.0.0-ci0032` published in November.

The ImageSharp repo is working well so we should copy that.

**Comment by tocsoft** [comment]
I'll try to take a look at this tonight, shouldn't take long to crib the required changes from the ImageSharp repo

**Comment by JimBobSquarePants** [comment]
Sweet man, cheers!
