### ISSUE TITLE
Log levels for Success and Failures should be tuned

### ISSUE THREAD

**Issue by ThomasSkyldahl** [SixLabors/ImageSharp.Web#190]
Hi
The current log levels defined here: [LoggerExtensions.cs](https://github.com/SixLabors/ImageSharp.Web/blob/5cb589cf3d04fc2a390bd3fce6f2da309e1c7223/src/ImageSharp.Web/Middleware/LoggerExtensions.cs#L23)
Are not defined in the best possible way to allow filtering unneeded log messages: Failures and Success all use Information or Debug level.

Can we tune this so that:
1. Error is logged with Error level.
2. Failure is logged as Warning level.
3. the rest is logged at Debug or Trace level depending on the how much they are in the 'hot' path.

We can make a pull request if you agree with the mentioned levels above.

**Comment by JimBobSquarePants** [comment]
Closing this. Please see the explanation in the related PR. https://github.com/SixLabors/ImageSharp.Web/pull/189#issuecomment-980019602
