### ISSUE TITLE
Image in cache is created for non supported formats

### ISSUE THREAD

**Issue by LuukVerhagen** [SixLabors/ImageSharp.Web#195]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp.Web
- [x] I have verified if the problem exists in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp.Web/issues) and [closed](https://github.com/SixLabors/ImageSharp.Web/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
If you request an image with an unsupported image type, an image is created in the cache. This way it is easier to DDOS the system.  

### Steps to Reproduce
-Add ImageSharp.Web to your asp.net core application
-Request an image with an unsupported type
-See in the console that a new image in the cache is created.

### System Configuration

- ImageSharp.Web version: 1.04
- Other Six Labors packages and versions: 1.04
- Environment (Operating system, version and so on): Windows 10 Pro 20H2 19042.1348
- .NET Framework version: .NET Core 5.0
- Additional information:

I temporarily solved the problem by the following code:

           
```
            services.AddImageSharp(x => 
            {
                x.OnParseCommandsAsync = c =>
                {
                    if (c.Commands.Count == 0)
                    {
                        return Task.CompletedTask;
                    }

                    // It's a good idea to have this to provide very basic security. 
                    // We can safely use the static resize processor properties. 
                    uint width = c.Parser.ParseValue<uint>(
                        c.Commands.GetValueOrDefault(ResizeWebProcessor.Width),
                        c.Culture);

                    uint height = c.Parser.ParseValue<uint>(
                        c.Commands.GetValueOrDefault(ResizeWebProcessor.Height),
                        c.Culture);

                    if (width > 4000 && height > 4000)
                    {
                        c.Commands.Remove(ResizeWebProcessor.Width);
                        c.Commands.Remove(ResizeWebProcessor.Height);
                    }


                    //If file extension is not supported, remove command.
                    {
                        string extension = c.Commands.GetValueOrDefault(FormatWebProcessor.Format);

                        SixLabors.ImageSharp.Formats.IImageFormat format = x.Configuration.ImageFormatsManager.FindFormatByFileExtension(extension);

                        if (format == null)
                        {
                            c.Commands.Remove(FormatWebProcessor.Format);
                        }
                    }

                    return Task.CompletedTask;
                };

            });
```

**Comment by JimBobSquarePants** [comment]
@LuukVerhagen Thanks for reporting this! Yes, we should definitely try to find an optimized way to avoid this.

**Comment by JimBobSquarePants** [comment]
@LuukVerhagen Looks like I've found a neat way of avoiding this without additional config hacks.
