### ISSUE TITLE
MissingMethodException when running on .NET Core 2.0

### ISSUE THREAD

**Issue by sebastienros** [SixLabors/ImageSharp.Web#2]
The usage of `EntityTagHeaderValue` is like this:
https://github.com/SixLabors/ImageSharp.Web/blob/9edd7eb054348503f6bb87fa13e03bc8ecfb87ae/src/ImageSharp.Web/Middleware/ImageContext.cs#L215

When an application using ImageSharp.Web is using a newer version of `Microsoft.Net.Http.Headers`, literally 2.0.0, then this constructor is not available anymore as it has been converted to a `StringSegment`.
It results in a `MissingMethodException` whenever the middleware is used.

There are two solutions:
- Target 2.0.0 only and reference the new packages
- Multi-target 1.4 and 2.0.0 with a conditional statement to switch to the other implementation

Please advise on your preferred solution and I will implement it. At this point I personally don't think supporting 1.4 still makes sense as you released after 2.0.

**Comment by tocsoft** [comment]
@JimBobSquarePants I think its your call on what we should be targeting here but I'm inclined to agree with @sebastienros  in that we should retarget onto 2.0.
