### ISSUE TITLE
Upgrade to ImageSharp 2.0 - MissingMethodException when using Web Middleware

### ISSUE THREAD

**Issue by robalexclark** [SixLabors/ImageSharp.Web#228]
Upgrading to ImageSharp 2.0. and using the SixLabor.ImageSharp.Web.Middleware (1.0.4) in .net 6.0 to resize images for the web.

In my Startup I have the middleware configured as follows:

    ```
        services.AddImageSharp(
                options =>
                {
                    options.Configuration = SixLabors.ImageSharp.Configuration.Default;
                    options.CachedNameLength = 8;
                })
                .SetRequestParser<QueryCollectionRequestParser>()
                //.SetMemoryAllocator(provider => ArrayPoolMemoryAllocator.CreateWithMinimalPooling())
                .Configure<PhysicalFileSystemCacheOptions>(options =>
                {
                    options.CacheFolder = "imagesharp-cache";
                })
                .SetCache<PhysicalFileSystemCache>()
                .SetCacheHash<CacheHash>()
                .AddProvider<PhysicalFileSystemProvider>()
                .AddProcessor<ResizeWebProcessor>();

```

I now get an error at runtime for the images fetched through the middleware (which causes a 500 error). The error in the console is:

System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<SixLabors.ImageSharp.Formats.IImageFormat> SixLabors.ImageSharp.Image.DetectFormatAsync(SixLabors.ImageSharp.Configuration, System.IO.Stream)'.
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.ProcessRequestAsync(HttpContext context, IImageResolver sourceImageResolver, ImageContext imageContext, IDictionary`2 commands)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by tocsoft** [comment]
2 things,
1. ImageSharp.Web version 1.x is only compatible with ImageSharp v1.x. We have yet to release a version on IS.Web with support ImageSharp 2.0.
2. SixLabor.ImageSharp.Web.Middleware (1.0.4) isn't our current release and you should probably be on v1.0.5 which has some bugfixes and allocation improvements.

I'm afraid you will have to wait until we manage to make a final cut of IS/web with support for imagesharp v2. Our main branch currently supports it but we are still working through some final changes first before pushing out to nuget, in the mean time you are free to try our alpha/nightly build off out myget feed https://www.myget.org/feed/sixlabors/package/nuget/SixLabors.ImageSharp.Web)

**Comment by sandcastle** [comment]
> I'm afraid you will have to wait until we manage to make a final cut of IS/web with support for imagesharp v2. Our main branch currently supports it but we are still working through some final changes first before pushing out to nuget

@tocsoft - to get a sense of if we should hold off using the alphas - are you able to give us a sense as to if the outstanding changes are stability related or features/refactoring?

**Comment by JimBobSquarePants** [comment]
You'll have to wait if you don't ant to use them. No guarantees can be provided at this stage.

Remember you're consuming an open source project which is provided [AS IS](https://github.com/SixLabors/ImageSharp.Web/blob/6912cbc719b6fbab16ff7c8c86e0567e57e0c7c7/LICENSE#L143-L151).
