### ISSUE TITLE
Core support 7

### ISSUE THREAD

**Issue by Alerinos** [SixLabors/ImageSharp.Web#231]
After upgrading to .net core 7 it stopped working, 0 errors. Zero information, it doesn't work.
Something has changed or is it enough to pick up the version of the package?

**Comment by JimBobSquarePants** [comment]
Hi @Alerinos 

.NET 7 is currently a [technical preview](https://devblogs.microsoft.com/dotnet/announcing-net-7-preview-1/) and as such we cannot support it at this time. When later builds ship we will test against thought builds and raise any upstream issues with the runtime team should they arise.

Please note. It's really important that you use the template when raising issues.
