### ISSUE TITLE
Question: Missing Configuration? Querystrings not applying.

### ISSUE THREAD

**Issue by Squalex1496** [SixLabors/ImageSharp.Web#24]
Hi, 

I recently discovered this package and from the looks of it, is exactly what i need for a .net core project. I'm testing it out on a fresh .Net Core 2.0 project and have installed via nuget the package and configured the Startup.cs's ConfigurationServices appropriately, by adding the line `services.AddImageSharp();` and have even added inside of the `Configure(IApplication app, IHotingEnvironment)` the line `app.UseImageSharpe()` Following this i went to test it out by appending a simple crop query string to an image `<img src="~/images/banner1.svg?width=100&height=100" alt="ASP.NET" class="img-responsive" />` and nothing seems to be taking any effect, **the image remains the same**. Is this a matter of further configuration or some issue? any help would be greatly appreciated, thanks!

**Comment by tocsoft** [comment]
@Squalex1496 ImageSharp and thus ImageSharp.Web doesn't have any support for svg. You normally wouldn't want to resize/rasterize svgs server side as that would defeat the purpose of them being scalable graphics, you would normally want to alter them via css directly as it will produce the best results.

**Comment by Squalex1496** [comment]
@tocsoft thanks for replying and about the SVG noted, however the problem still arose when i used any other image format, example `<img src="images/drill-1.jpg?width=300&height=600" alt="img"/>` the image remains exactly the same and no processing has been done to it whatsoever. I've followed the guidelines to the letter but maybe i've missed something? 

P.S.
I'm testing it out on a fresh .Net Core 2.0 Template with nothing else added or featured, i intend to implemente this in a Nop Commerce project. I think that the ImageSharp.Web would make managing images for the client much easier. Thanks.

**Comment by andymac4182** [comment]
@Squalex1496 Are you able to publish the code to a repo? My guess would be an ordering issue in `Startup`. I had a similar issue when I did the ordering wrong.

**Comment by JimBobSquarePants** [comment]
Good point @andymac4182 Ordering is important. We have to be declare before the static file middleware for example. 

@Squalex1496 There's a [sample application](https://github.com/SixLabors/ImageSharp.Web/blob/8fe72d7721b28361f9d27710e5ce698db3f76c64/samples/ImageSharp.Web.Sample/Startup.cs) within the repository which has example setup for pretty much every scenario. In your case (without additional configuration) your startup file should look something like this.

``` c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using SixLabors.ImageSharp.Web.DependencyInjection;

namespace SixLabors.ImageSharp.Web.Sample
{
    public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            // Add the default service and options.
            services.AddImageSharp();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole();

            app.UseExceptionHandler();
            app.UseDeveloperExceptionPage();
            app.UseDefaultFiles();
            app.UseImageSharp();
            app.UseStaticFiles();
        }
    }
}
```

**Comment by Squalex1496** [comment]
@JimBobSquarePants & @andymac4182 yes that was exactly the problem, all i needed to change was the order. Tested it out and its working great! I've started integrating this inf a Nop Commerce project and I think that its the perfect tool for anyone that needs the processing done on their images for the site, great work and many thanks!

**Comment by JimBobSquarePants** [comment]
Great stuff! Glad we could help 😄

**Comment by untiedshoes** [comment]
> @Squalex1496 yes that was exactly the problem, all i needed to change was the order. Tested it out and its working great! I've started integrating this inf a Nop Commerce project and I think that its the perfect tool for anyone that needs the processing done on their images for the site, great work and many thanks!

I know this was a way back now, but any chance you could give some insights into how you incorporated imageSharp.Web into nopCommerce (4.00) - I'm having the same issue at the moment, and for the life of me, can I not get it working!

Regards,
Craig
