### ISSUE TITLE
MissingMethodException when using the latest ImageSharp release

### ISSUE THREAD

**Issue by kroymann** [SixLabors/ImageSharp.Web#251]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp.Web
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp.Web/issues) and [closed](https://github.com/SixLabors/ImageSharp.Web/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp.Web version

1.0.5

### Other Six Labors packages and versions

ImageSharp 2.1.0

### Environment (Operating system, version and so on)

Windows

### .NET Framework version

NET 6.0

### Description

After upgrading ImageSharp from version 1.0.4 to version 2.1.0, the latest official release of ImageSharp.Web no longer works and throws the following exception at runtime:
```
System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<SixLabors.ImageSharp.Formats.IImageFormat> SixLabors.ImageSharp.Image.DetectFormatAsync(SixLabors.ImageSharp.Configuration, System.IO.Stream)'.
  at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.ProcessRequestAsync(HttpContext context, IImageResolver sourceImageResolver, ImageContext imageContext, IDictionary`2 commands)
  at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
```

I believe this is because there were function signature changes made in v2.0.0 (eg: https://github.com/SixLabors/ImageSharp/pull/1856) that require a rebuild of ImageSharp.Web.  There have also been a number of important fixes that haven't yet been released (eg: #222).  Would it be possible to get a new official release of ImageSharp.Web published to NuGet?

### Steps to Reproduce

Build a project using the latest release of ImageSharp and ImageSharp.Web, and then try to process any image request

**Comment by JimBobSquarePants** [comment]
Hi @kroymann 

Thanks, yeah that’s known. They’re not compatible.

I’m trying to get a V2 of ImageSharp.Web shipped that is designed to work with ImageSharp  V2.

**Comment by kroymann** [comment]
Out of curiousity, what work remains to create this "ImageSharp.Web V2"?  For my testing purposes, I've created a pre-release nuget package from the latest commit in the master branch, pushed that to our private package feed, and am consuming that package in our application.  Initial smoke-testing seemed OK.  Is there some reason you're aware of that I shouldn't consider rolling this out to our production servers (after more testing of course)?

**Comment by JimBobSquarePants** [comment]
It should be solid but there's two things left to deal with.

1. Form this libraries perspective there's HMAC support #250 which I think we're close to getting things merged.
2. Upstream we had a memory access violation reported against v2.1.0 https://github.com/SixLabors/ImageSharp/issues/2075#issuecomment-1088884749 I'm really concerned about that and do not want to ship this library targeting a version with those kinds of errors. Unfortunately we've not got test images yet.

**Comment by aramdata** [comment]
i have same problem i solve that by [myget.org](https://www.myget.org/F/sixlabors/api/v3/index.json) package.

**Comment by JimBobSquarePants** [comment]
v2.0.0 is on NuGet now so I can close this.
