### ISSUE TITLE
UriAbsoluteLowerInvariantCacheKey is not backwards compatible

### ISSUE THREAD

**Issue by deanmarcussen** [SixLabors/ImageSharp.Web#254]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp.Web
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp.Web/issues) and [closed](https://github.com/SixLabors/ImageSharp.Web/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp.Web version

2.0.0

### Other Six Labors packages and versions

as per ImageSharp.Web

### Environment (Operating system, version and so on)

Windows

### .NET Framework version

6

### Description

`UriAbsoluteLowerInvariantCacheKey` is not backwards compatible with images when they have a `PathBase`

the old cache key behaviour

```
            var sb = new StringBuilder(context.Request.Host.ToString());

            string pathBase = context.Request.PathBase.ToString();
            if (!string.IsNullOrWhiteSpace(pathBase))
            {
                sb.AppendFormat("{0}/", pathBase);
            }

            string path = context.Request.Path.ToString();
            if (!string.IsNullOrWhiteSpace(path))
            {
                sb.Append(path);
            }

            sb.Append(QueryString.Create(commands));

            return sb.ToString().ToLowerInvariant();
```

would produce a key that read like this
`localhost:44300/agency1//media/portfolio/1.jpg?width=600&height=480&rmode=stretch`

note the `//` between the `PathBase` and the `Path`

the new `UriAbsoluteLowerInvariantCacheKey` doesn't have this bug, which means the old cache key is invalid.

`localhost:44300/agency1/media/portfolio/5.jpg?width=600&height=480&rmode=stretch`

We can work around this by testing the pathbase value and appending a double slash to it, with a custom cache key processor.

```
    public class BackwardsCompatibleCacheKey : ICacheKey
    {
        public string Create(HttpContext context, CommandCollection commands)
        {
            var pathBase = context.Request.PathBase;
            if (pathBase.HasValue)
            {
                pathBase = new PathString(pathBase + "//");
            }

            return CaseHandlingUriBuilder.BuildAbsolute(CaseHandlingUriBuilder.CaseHandling.LowerInvariant, context.Request.Host, pathBase, context.Request.Path, QueryString.Create(commands));
        }
    }
```

More of an informational issue than anything else, feel free to agree and close.

We'll probably use the backwards compatible version, just to prevent doubling up on cache sizes

### Steps to Reproduce

Upgrade from 1 to 2

**Comment by JimBobSquarePants** [comment]
@deanmarcussen https://github.com/SixLabors/ImageSharp.Web/blob/main/src/ImageSharp.Web/Caching/LegacyV1CacheKey.cs should give you what you need.

**Comment by deanmarcussen** [comment]
Yup, that'll do it. but I might keep mine, since you improved the string creation :)

needed this too
```
          .Configure<PhysicalFileSystemCacheOptions>(options =>
                {
                    options.CacheFolderDepth = 12;
                })
```

**Comment by JimBobSquarePants** [comment]
>Yup, that'll do it. but I might keep mine, since you improved the string creation :)

Yeah, it's MUCH better now. Wish I'd used my brain and used your implementation for the legacy stuff. 

Was just about to add the additional config info here. Will be adding info to the documentation for people upgrading.
