### ISSUE TITLE
WebP images don't auto orient based on EXIF metadata

### ISSUE THREAD

**Issue by SigmundurMorkore** [SixLabors/ImageSharp.Web#259]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp.Web
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp.Web/issues) and [closed](https://github.com/SixLabors/ImageSharp.Web/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp.Web version

2.0.0

### Other Six Labors packages and versions

2.1.1

### Environment (Operating system, version and so on)

Linux

### .NET Framework version

5

### Description

When formatting a jpg image to webp using `?format=webp` the resulting webp image does not orient itself according to the jpg's exif orientation metadata.

Formatted as JPG, the image is oriented correctly. Formatted as WebP, the image is oriented sideways.

### Steps to Reproduce

Try to format a JPG image with orientation metadata to WebP with the following parameters:

`?format=webp`

The image will not be oriented according to the metadata.

**Comment by brianpopow** [comment]
@SigmundurMorkore can you provide the image in question?

**Comment by SigmundurMorkore** [comment]
Right sorry, was in a hurry when writing this issue up. Here you go @brianpopow :)

This is the JPG being formatted with: `?width=730&height=730&rmode=crop`
![20220131_095657](https://user-images.githubusercontent.com/39065262/166918475-ec1cf275-fdc3-4efd-bc5d-6bbca62c6242.jpg)
https://hk.cdn.fo/savn/txre1cva/20220131_095657.jpg?width=730&height=730&rmode=crop&s=7vf1XiXI9f3Z8qBWADtVEuJC6pg

And then this is the same JPG but being converted to WebP with: `?format=webp&width=730&height=730&rmode=crop`
[20220131_095657.webp.zip](https://github.com/SixLabors/ImageSharp.Web/files/8630982/20220131_095657.webp.zip)
https://hk.cdn.fo/savn/txre1cva/20220131_095657.jpg?format=webp&width=730&height=730&rmode=crop&s=3ceq5WFoMMC_SBmzd73zGAaPZcQ

**Comment by SigmundurMorkore** [comment]
Made a discovery! It seems Firefox and Chrome both fail to rotate the webp image. But Safari does manage to rotate the webp image correctly. Could this instead be a browser issue?

**Comment by SigmundurMorkore** [comment]
We've tried replicating our issue with JPG, but have only been able to replicate the issue when the image format is WebP. So considering #258 has an issue with JPG, it would seem to be that these are different issues 🤷‍♂️

**Comment by brianpopow** [comment]
@SigmundurMorkore this really looks to me like a issue with the auto orient of the viewer (=browser). The Exif Information is preserved with both:

- ?width=730&height=730&rmode=crop
- ?format=webp&width=730&height=730&rmode=crop

The browsers I tested: chrome, opera, firefox seem to ignore exif with webp and with jpg they all rotate the image according to exif.

Not sure yet how #258 is related. I have not looked into that so far.

**Comment by SigmundurMorkore** [comment]
Yeah that would make sense... I wonder why I am unable to find anyone else having this issue with webp in browsers.

Is it possible to actually rotate the image and removing the orientation exif metadata with ImageSharp.Web?

**Comment by SigmundurMorkore** [comment]
This actually seems to also be an issue with PNG and AVIF: https://zpl.fi/exif-orientation-in-different-formats/

**Comment by brianpopow** [comment]
> So it would seem to be ideal to be able to actually rotate the image (and removing the orientation metadata)

I think we dont have that yet in ImageSharp.Web, @JimBobSquarePants please correct me if I am wrong. Should we maybe add a `AutoOrientProcessor`?

**Comment by SigmundurMorkore** [comment]
The `AutoOrientProcessor` would be very handy! 👍

**Comment by brianpopow** [comment]
It seems we had `AutoOrientProcessor` at some point, but it was removed again: [PR220](https://github.com/SixLabors/ImageSharp.Web/pull/220)

I think its worth reconsidering this, as I believe auto orient makes sense also without resizing.

**Comment by SigmundurMorkore** [comment]
We have added our own AutoOrientProcessor for now (following the code in #220), which solves our issue.

Agree it is worth reconsidering adding it to ImageSharp.Web officially.

**Comment by JimBobSquarePants** [comment]
Yeah let’s re-add it. Was hoping to avoid it to preserve consistency with the CSS spec but with all those daft browser bugs we’ll need a backup plan.

**Comment by dlemstra** [comment]
The `AutoOrientProcessor` was removed because there was already an `orient` option in the `ResizeWebProcessor` that is enabled by default. Isn't this a bug instead the `ResizeWebProcessor` instead?

**Comment by JimBobSquarePants** [comment]
I wish it was a bug in our code. 

It’s definitely a browser issue. We’re tracking the EXIF properties properly and orienting accordingly. Browsers are just super poor at implementing the CSS spec for the different image formats. That’s what happens when you cobble together a bunch of different libraries I guess…

**Comment by JimBobSquarePants** [comment]
Since we can't fix browser issues I would consider #260 to be an adequate workaround for now.
