### ISSUE TITLE
AWS S3 Transfert Acceleration

### ISSUE THREAD

**Issue by mdupras** [SixLabors/ImageSharp.Web#262]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp.Web
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp.Web/issues) and [closed](https://github.com/SixLabors/ImageSharp.Web/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp.Web version

2.0.0

### Other Six Labors packages and versions

2.1.1

### Environment (Operating system, version and so on)

Ubuntu 20.04

### .NET Framework version

6.0

### Description

I'm trying to use an S3 Transfert acceleration endpoint as describe here.
https://docs.aws.amazon.com/AmazonS3/latest/userguide/transfer-acceleration-getting-started.html

When I try to use the Endpoint option in the current options I get this Exception.  
```
---> Amazon.Runtime.AmazonClientException: Specify a region using AmazonS3Config.RegionEndpoint or AmazonS3Config.AuthenticationRegion to use S3 accelerate.
at Amazon.S3.AmazonS3Config.Validate()
at Amazon.Runtime.AmazonServiceClient..ctor(AWSCredentials credentials, ClientConfig config)
at Amazon.Runtime.AmazonServiceClient..ctor(String awsAccessKeyId, String awsSecretAccessKey, ClientConfig config)
at Amazon.S3.AmazonS3Client..ctor(String awsAccessKeyId, String awsSecretAccessKey, AmazonS3Config clientConfig)
```

I think we simply need to add the region from the current config. If it's
```AmazonS3Config config = new() { ServiceURL = options.Endpoint, ForcePathStyle = true, AuthenticationRegion = options.Region };```

According to the Amazon SDK, the `AuthenticationRegion` is optional.
```
    /// <summary>
    /// Gets and sets the AuthenticationRegion property.
    /// Used in AWS4 request signing, this is an optional property;
    /// change it only if the region cannot be determined from the
    /// service endpoint.
    /// </summary>
    public string AuthenticationRegion
```

### Steps to Reproduce

- Have a S3 transfert accelerated bucket. https://docs.aws.amazon.com/AmazonS3/latest/userguide/transfer-acceleration-getting-started.html
- Use an AWSS3StorageCache or AWSS3StorageImageProvider with SixLabors.ImageSharp.Web

**Comment by JimBobSquarePants** [comment]
Fixed via #263
