### ISSUE TITLE
v1.0.5 unsupported format prevents all processing

### ISSUE THREAD

**Issue by matthewcare** [SixLabors/ImageSharp.Web#267]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp.Web
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp.Web/issues) and [closed](https://github.com/SixLabors/ImageSharp.Web/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp.Web version

1.0.5 - 2.0.0

### Other Six Labors packages and versions

ImageSharp 1.0.4 / 2.0.0

### Environment (Operating system, version and so on)

Windows 11 Pro 21H2 22000.675 

### .NET Framework version

.net 5/6

### Description

Debatable as to whether my specific use case constitutes a breaking change, however  PR #197 (and the subsequent 1.0.5+ releases) has caused images to not process at all if the format is invalid.

I have a codebase which is preparing for ImageSharp V2, and webp support, so my url generation added `format=webp` so that when I upgraded to v2 there wouldn't be any changes to make. Due to package restrictions I cannot upgrade to 2.0.0 quite yet.

Prior to v1.0.5 the format was ignored, but the resizing was still processed.

For example, a 2000x2000px image being processed with the query string
`?width=1200&height=100&format=sdsfsdfs` would still result in an image size of 1200x100
whereas now nothing is processed.

I gather from #195 that this was intentional to not cache invalid items, however I think that if there is an invalid format, that all other processes should still take place.

Looking forward to hearing people's thoughts :)

### Steps to Reproduce

Attempt to resize an image with an invalid format in the query string. 
In version 1.0.4 the image would resize correctly, and the format is ignored.
In version 1.0.5 / 2.0.0  the image isn't processed at all.

**Comment by JimBobSquarePants** [comment]
Hi @matthewcare 

I'm afraid we cannot make that an option. The functionality is specifically designed to avoid DDOS attacks and we value security over everything.

**Comment by matthewcare** [comment]
Hi @JimBobSquarePants 

Apologies for commenting on an issue marked as complete.

I understand the DDOS implication, but what I was suggesting was that if the format wasn't valid it would stripped from the query string before processing started.

`?width=800&format=invalid` would become `?width=800`

Wouldn't this mean that there would only be one item cached and returned - regardless of if someone made requests with a thousand different invalid formats?
