### ISSUE TITLE
Add Custom Parameter to the request url for caching

### ISSUE THREAD

**Issue by sarunsankar** [SixLabors/ImageSharp.Web#275]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

1.0.0.0

### Other ImageSharp packages and versions

1.0.0.0

### Environment (Operating system, version and so on)

Windows

### .NET Framework version

.Net Core 3.1

### Description

We are using **PhysicalFileSystemCache** as the caching mechanism for Imagesharp . The issue is that we don't need to change the caching duration, but we need to pass an additional parameter like modifiedDate and provide the value from client side so that we can cache the latest image with the new request URL as the cache key.Our current approach is to derive a **customwebprocessor** by inheriting **ResizeWebProcessor** and adding a property called **ModifiedDate**, but it's not working. Could you please explain how to pass this parameter instead of width, height, sampler, etc.
![image](https://user-images.githubusercontent.com/35756748/174017586-2d82bd76-ff10-4a82-a8b1-4267a2a35b82.png)
![image](https://user-images.githubusercontent.com/35756748/174017684-caed05f0-afab-4337-a428-6f1b7ca0b8b2.png)

### Steps to Reproduce

    public class CustomWebProcessor : ResizeWebProcessor
    {
        public const string ModifiedDate = "modifiedDate";
    }

 services.AddImageSharpCore()
                .SetRequestParser<QueryCollectionRequestParser>()
                .SetMemoryAllocatorFromMiddlewareOptions()
                .SetCache(provider => new PhysicalFileSystemCache(
                    provider.GetRequiredService<IHostingEnvironment>(),
                    provider.GetRequiredService<MemoryAllocator>(),
                    provider.GetRequiredService<IOptions<ImageSharpMiddlewareOptions>>())
                {
                    Settings =
                    {
                        [PhysicalFileSystemCache.Folder] = PhysicalFileSystemCache.DefaultCacheFolder
                    }
                })
                .SetCacheHash<CacheHash>()
                .AddProvider<TemplateFamilyImageFileProvider>()
                .AddProvider<POSImageFileProvider>()
                //.AddProcessor<ResizeWebProcessor>()
                .AddProcessor<FormatWebProcessor>()
                .AddProcessor<CustomWebProcessor>()
                .AddProcessor<BackgroundColorWebProcessor>();

**Comment by ronaldbarendse** [comment]
@sarunsankar I'm pretty sure you won't get support here if you're still on version 1.0.0, so better upgrade to the latest possible first (at least the latest patch version).

Inheriting the `ResizeWebProcessor` and only adding a property won't do much indeed: you at least need to add it to the list in the `Commands` property. I'm not sure why you would want to include the last modified date though, as it doesn't affect processing of the image and ImageSharp already re-generates the image if the file has changed: https://github.com/SixLabors/ImageSharp.Web/blob/f65a29535f0fd2f14556f1104d1f9d5679b6e5a2/src/ImageSharp.Web/Middleware/ImageSharpMiddleware.cs#L519-L528

If you just want to invalidate the browser/client cache, simply adding a cache buster value to the URL (like `&v=2`) will suffice. You could use the modified date for this if you want, but then you'd need to fetch the current value when generating the image URL and can leave the ImageSharp config untouched...

**Comment by JimBobSquarePants** [comment]
Hi @sarunsankar 

As @ronaldbarendse correctly points out ImageSharp.Web automatically detects changes to the source file. Any browser cache busting should be done with a querystring param.

For the future, please note that the Issue tracker is for raising issues only, not asking questions. We have a [dedicated discussions channel](https://github.com/SixLabors/ImageSharp.Web/discussions/categories/q-a) for that.
