### ISSUE TITLE
Exception on simple usage

### ISSUE THREAD

**Issue by dodyg** [SixLabors/ImageSharp.Web#28]
The library version I am using is 1.0.0-beta0003. I am using ASP.NET Core 2.1 with standard configuration.

```
services.AddImageSharp();
```

```
    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.0" />
```

![exception](https://user-images.githubusercontent.com/1761249/41875107-2c4f9968-78ca-11e8-8c10-6a5829b6c1b4.png)

**Comment by JimBobSquarePants** [comment]
You need to update your underlying ImageSharp references and if it still persists (It shouldn’t) your System.Memory references.
