### ISSUE TITLE
Middleware is very susceptible to unreasonable processing commands

### ISSUE THREAD

**Issue by lord-executor** [SixLabors/ImageSharp.Web#285]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp.Web
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp.Web/issues) and [closed](https://github.com/SixLabors/ImageSharp.Web/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp.Web version

2.0.2

### Other Six Labors packages and versions

-

### Environment (Operating system, version and so on)

win10

### .NET Framework version

6.0.107

### Description

A very simple attack to any system that uses the SixLabors.ImageSharp.Web middleware with its out-of-the-box configuration is this: Create a request that resizes an image to scale its width to an extremely large size while preserving the aspect ratio. Example: "/images/test.jpg?quality=90&width=300000"

This will likely kill the target system by exhausting its memory - that is at least what happened in my simple demo app. I am aware that it is _possible_ to mitigate these types of attacks with the mechanism described in https://github.com/SixLabors/ImageSharp.Web/discussions/139, but:
* It really seems a bit irresponsible to allow this kind of transformation in the default configuration.
* The simple default sanitation mentioned in that discussion has been **removed** with the introduction of HMAC authentication and even if it was still there, it would only work if both width AND height are greater than 4000.
* HMAC authentication really isn't a viable replacement for some sane default restrictions on image sizes since HMAC can only be used in _certain_ scenarios and to prevent _certain_ attacks.
* The documentation https://docs.sixlabors.com/articles/imagesharp.web/processingcommands.html doesn't mention anything about this type of problem.

### Steps to Reproduce

Run a simple server that contains the SixLabors.ImageSharp.Web middleware and make sure that a test image is available. Access the test image by adding the query string "width=300000" and be ready to kill the process as it will very quickly consume all of your memory. Works with ANY image, but I have attached my "test.jpg" for _ironic convenience_.

### Images

![test](https://user-images.githubusercontent.com/286947/183254927-a583209f-5808-4581-95d8-1f5da67edfc9.jpg)

**Comment by JimBobSquarePants** [comment]
I’m going to ban you from the organisation as a result of your attitude and communication here. We have a code of conduct which you have blatantly ignored. 

I hope you learn something from this interaction.
