### ISSUE TITLE
AsyncKeyLock should use a ConcurrentDictionary

### ISSUE THREAD

**Issue by sebastienros** [SixLabors/ImageSharp.Web#31]
Gut feeling, but it looks like the hard lock is less efficient than what a ConcurrentDictionary would do. I ran https://github.com/benaadams/Ben.BlockingDetector (/cc @benaadams) and it showed up in the logs.

**Comment by JimBobSquarePants** [comment]
Interesting... Would be really useful if you could benchmark this, we’re planning a release very soon.

**Comment by JimBobSquarePants** [comment]
@sebastienros I've had another look at the class and I'm struggling to see how I can do it with `ConcurrentDictionary`.

**Comment by sebastienros** [comment]
It's possible that there are details in the algorithm I didn't see that would prevent it. I am checking again.

**Comment by JimBobSquarePants** [comment]
Thanks, my brain is pretty fried at the moment.
