### ISSUE TITLE
API suggestion for IImageResolver and IImageCache

### ISSUE THREAD

**Issue by antonfirsov** [SixLabors/ImageSharp.Web#32]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp.Web
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp.Web/issues) and [closed](https://github.com/SixLabors/ImageSharp.Web/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Problem
Currently cached images are loaded into memory unnecessarily: it should be enough to copy the file/azure blob/redis/memory etc. stream into `response.Body` without reading the full contents.

### Solution
`IImageCache.GetAsync(...)`, `IImageCache.SetAsync(...)` and `IImageResolver.ResolveImageAsync()`  should work with a dedicated abstract `ICachedImage` object instead of an in-memory buffer:

```C#
public interface ICachedImage
{
    Stream OpenRead();
    Stream OpenWrite();
}
```
For me it seems this API can cover all the use cases which are being solved with in-memory buffers at the moment:
- Read and write `FormattedImage`
- Copy contents to and from other streams (eg. `response.Body`, `MemoryStream`)

**Comment by JimBobSquarePants** [comment]
Yep, I agree completely. This would remove that copy, and simplify the API. 

I don't know about `ICachedImage` as the interface name though. It would feel odd to me in the context of `IImageResolver.ResolveImageAsync()`
