### ISSUE TITLE
Pooling output stream buffer

### ISSUE THREAD

**Issue by aevitas** [SixLabors/ImageSharp.Web#33]
In the `ImageSharpMiddleware` class, the following comment currently exists:

> // TODO: How to prevent the allocation in outStream? Passing a pooled buffer won't let stream grow if needed.

This could be achieved by a custom `MemoryStream`-esque implementation that grows the buffer by using an array pool or a buffer manager rather than allocating on the heap. (`MemoryStream` performs this allocation in its `Capacity` property, which makes it a poor candidate for inheriting and changing that specific behaviour, so we'd effectively have to roll our own `Stream` to prevent said allocation)

I reckon in high-performance scenarios the difference between having a pooled vs allocated output stream could be significant. 

Is this middleware component part of the official release, and would it be worth it to invest the time to optimise this part of the middleware? If so, I could have a stab at it.

**Comment by JimBobSquarePants** [comment]
https://referencesource.microsoft.com/#System.Runtime.Remoting/channels/core/chunkedmemorystream.cs

**Comment by aevitas** [comment]
I'll have a look at the PR that includes the memory management from SixLabors.Core and work out a way to integrate it neatly.
