### ISSUE TITLE
"Sending image. Request uri" log Should be debug not information

### ISSUE THREAD

**Issue by Myster** [SixLabors/ImageSharp.Web#363]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp.Web
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp.Web/issues) and [closed](https://github.com/SixLabors/ImageSharp.Web/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp.Web version

3.1.0

### Other Six Labors packages and versions

SixLabors.ImageSharp 3.1.2

### Environment (Operating system, version and so on)

Windows 11

### .NET version

8.0

### Description

logging is too verbose, the log template `Sending image. Request uri: '{Uri}'. Cached Key: '{Key}'` is 73% of the rows in my log file for my Umbraco website.

This issue is in the latest version here: https://github.com/SixLabors/ImageSharp.Web/blob/main/src/ImageSharp.Web/Middleware/LoggerExtensions.cs#L34

### Steps to Reproduce

Run an umbraco (v13) website with some images using cropping

**Comment by Myster** [comment]
I was not aware of this feature to workaround this issue, we can change JUST image sharp log level without affecting the others. (thanks Richard) here: https://our.umbraco.com/forum/using-umbraco-and-getting-started/111383-how-to-disable-sending-image-log

You can specify it in the Override property, as shown below:

```
{
  ...
  "Serilog": {
    "MinimumLevel": {
      "Default": "Information",
      "Override": {
        ...
        "SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware": "Warning"
      }
    }
  },
  ...
}
```

**Comment by JimBobSquarePants** [comment]
We use the same defaults as the ASP.NET Core  static file handler. This is the correct default level. 

As you can see, the log level is configurable using the same conventions as all other loggers. Ultimately users are responsible for setting log levels. 

Note. In your example config the default level is  “Information”
