### ISSUE TITLE
Intermittent build failures on Travis.

### ISSUE THREAD

**Issue by JimBobSquarePants** [SixLabors/ImageSharp.Web#41]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp.Web
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp.Web/issues) and [closed](https://github.com/SixLabors/ImageSharp.Web/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Ever since we merged the Lock Free PR #34 we've had intermittent build failures on Travis where tests simply time out. It could be a poorly written test, it could be something more sinister. We should investigate.

/cc @sebastienros 

https://travis-ci.org/SixLabors/ImageSharp.Web/builds

**Comment by sebastienros** [comment]
Any idea if specific tests are failing? Couldn't figure from my mobile.

**Comment by JimBobSquarePants** [comment]
The CI output doesn't actually tell you it just sits waiting until it times out.

I skipped the following two tests though and the build passed.

https://github.com/SixLabors/ImageSharp.Web/blob/8da968c85b225632c140ce24af8dcc4e7b6dc76a/tests/ImageSharp.Web.Tests/Caching/AsyncKeyLockTests.cs#L17

**Comment by sebastienros** [comment]
Maybe the tests run in parallel and go in deadlock.

**Comment by JimBobSquarePants** [comment]
Looks like that's the case. I'm just calling individual tests from a single method now and that is working. 

I imaging it's probably caused by my use of thread sleep inside the tasks. I'll rewrite the tests sometime on the future.

**Comment by JimBobSquarePants** [comment]
Reopening as the passing appeared to be random..

**Comment by JimBobSquarePants** [comment]
Bad test. Should have been using `TaskDelay()`
