### ISSUE TITLE
Bug in default implementation of cache hash creation?

### ISSUE THREAD

**Issue by vyliniem** [SixLabors/ImageSharp.Web#45]
Hi,
I ran into caching issues while adding this middleware into my app, all matched urls (which are in the form of `/imagepool/3a47ac8a-c95c-4a6c-a96c-94613d3f567a.ext`) returned the same image, the one which was accessed first. Adding a processing parameter caused the correct image being loaded, but again trying to load other images with the same parameters returned the firstly accessed image.

So I took a look at the default CacheHash implementation and to me it looks like the hash is generated from the empty(?) buffer from the pool. Seems the url-value is only used to get the extension and the size of the buffer, thus if the hash is calculated from a buffer of zeroes(?) it only changes if the buffer size  changes. After switching to my own implementation of the CacheHash everything worked as expected.

https://github.com/SixLabors/ImageSharp.Web/blob/2d788422297e9a898472bc0199e0d66fcbddada9/src/ImageSharp.Web/Caching/CacheHash.cs#L46

**Comment by JimBobSquarePants** [comment]
Oh wow! That’s some egg on my face! I messed up there. 

Thanks for raising this I’ll get a new beta out in a couple of hours

**Comment by JimBobSquarePants** [comment]
Fixed in 1.0.0-beta0005

https://www.nuget.org/packages/SixLabors.ImageSharp.Web/1.0.0-beta0005
