### ISSUE TITLE
Can not add ImageSharp service to StartUp.cs in VS 2017

### ISSUE THREAD

**Issue by rswetnam** [SixLabors/ImageSharp.Web#47]
### Prerequisites

In was able to successfully install ImageSharp.Web in VS 2017 with the command:  
`install-package SixLabors.ImageSharp.Web -version 1.0.0-beta0005`  However, when I tried to add the line:
`services.AddImageSharp();` to StartUp.cs, VS 2017 did not recognize the name space - I got an intellisense error and was unable to proceed.  This seems to be the same as the problems reported in issue #190  except for the fact that I am using the package manager command line to install. 

### Steps to Reproduce
I tried this in both an existing project and a brand-new one.  

### System Configuration
Windows 10 VS2017 vanilla - latest version

**Comment by JimBobSquarePants** [comment]
There is an entire sample application in the repository. `Ctrl +.` in Visual Studio also brings up intellisense options.

Feel free to create a PR adding the using to the readme.
