### ISSUE TITLE
ImageSharp.Web 

### ISSUE THREAD

**Issue by tocsoft** [SixLabors/ImageSharp.Web#5]
### Description
This issue is designed to capture the architecture and tasks required to build an extensible library for parsing URL API instructions and caching the result.

Feel free to discuss below. We'll assign specific issues for functional components as we determine them.

### Basic Requirements 

- [x] Asp.NET Core Middleware to capture valid requests
- [x] Extensible configuration for Caching, ImageServices, and Processing. Must be secure.
- [x] `IImageService` implementations for physical file system and remote images. 
- [x] `IDistributedCache` implementation for physical file system that can be switched out for Redis, Azure, etc. How do we handle cleanup, Response codes?
- [x] Fast, low collision hashing of URL for cache implementations.

### Pipeline

The following gives an overall summary of the image processing pipeline.

1. Request is intercepted by Middleware (Authorisation?)
2. `IImageService` is assigned using URL prefix pattern matching (Regex?)
3. `IImageService` determines validity of request and attempts to return stream containing image.
4. `IDistributedCache` implementation checks if file exists. (Redirect if exists?)
5. Not cached? URL querystring params are parsed for matching processor.
6. Image is processed by matches via fluent API. 
7. Result is cached and image served.
8. Cleanup of expired cached files. (How?, When?)

# Edit

**Updated Requirements and Pipeline below**

### Basic Requirements 

- [x] Asp.NET Core Middleware to capture valid requests
- [x] Extensible configuration for Parsing, Resolving, Processing, and Caching. Must be secure
- [ ] <strike>Configuration for handling EXIF metadata</strike> Managed via `OnBeforeSave`
- [x] `IRequestParser` implementation for parsing requests for command string that can be switched out
- [x] `IImageResolver` implementation collection for physical file system that 
- [x] Extensible `CommandParser` implementation for converting commands into real values for processing. 
- [x] `IImageWebProcessor` for Resize
- [ ] <strike>`IImageWebProcessor` for Quality</strike> Managed by configuring individual formats.
- [x] `IImageWebProcessor` for Format
- [x] `IImageWebProcessor` for BackgroundColor
- [x] `IImageCache` implementation for physical file system that can be switched out for Azure, etc.
- [x] Fast, low collision hashing of URL for cache implementations
- [x] `ILogger` based logging
- [ ] <strike/>`TagHelper` for generating `img`, `picture` markup</strike> Out of scope.

### Pipeline

The following gives an overall summary of the image processing pipeline.

1. Request is intercepted by Middleware
2. `IUriParser` extracts commands; if not found, exit
3. `IImageResolver` is assigned using `Match()` method
4. `IImageResolver` determines validity of request and attempts to return stream containing image.
5. `IImageCache` implementation checks if file exists. (Returns correct response)
6. Not cached? URL querystring params are parsed for matching processor.
7. `IImageWebProcessor` implementations process the image
8. Result is cached and image served.

_copied from SixLabors/ImageSharp#216_

**Comment by mudrz** [comment]
Great project, I was just wondering if you have any tentative timeline plans for the release?
1 month, 1 year?

**Comment by JimBobSquarePants** [comment]
Q1 2018. Basically as soon as MS ship NetStandard 2.1 (We need to wait for final System.Memory release)

**Comment by psijkof** [comment]
That's why I'm getting this?

```
fail: SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware[1]
The image 'https://localhost:44394/assets/img/catalogos/Bauen.jpg?width=300' could not be processed
System.MissingMethodException: Method not found: '!0 System.ReadOnlySpan`1.get_Item(Int32)'.
    at SixLabors.ImageSharp.Formats.Bmp.BmpImageFormatDetector.IsSupportedFileFormat(ReadOnlySpan`1 header)
    at SixLabors.ImageSharp.Formats.Bmp.BmpImageFormatDetector.DetectFormat(ReadOnlySpan`1 header)
    at SixLabors.ImageSharp.Image.<>c__DisplayClass0_0.<InternalDetectFormat>b__0(IImageFormatDetector x)
    at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
    at System.Linq.Enumerable.TryGetLast[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
    at SixLabors.ImageSharp.Image.InternalDetectFormat(Stream stream, Configuration config)
    at SixLabors.ImageSharp.Image.Decode[TPixel](Stream stream, Configuration config)
    at SixLabors.ImageSharp.Image.WithSeekableStream[T](Stream stream, Func`2 action)
    at SixLabors.ImageSharp.Image.Load[TPixel](Configuration config, Stream stream, IImageFormat& format)
    at SixLabors.ImageSharp.Image.Load[TPixel](Configuration config, Byte[] data, IImageFormat& format)
    at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
```

**Comment by JimBobSquarePants** [comment]
@psijkof You need to add an explicit reference to the ImageSharp beta4 nuget package. 

I want to get a release out which fixes this but there's beta 5 coming soon which I really should wait for.

**Comment by tmarman** [comment]
I'm looking at using this to replace ImageResizer on aspnetcore. I have all of my images stored on Azure Blob Storage (a pattern I've also used on GCS or S3). 

Is there any way for me to write something that ties into the pipeline to parse the path and load from this blob storage?

**Comment by JimBobSquarePants** [comment]
Absolutely. You need to implement an `IImageProvider` and `IImageResolver` then register both via dependency injection. We do plan to release an official plugin that does this for you.

**Comment by JimBobSquarePants** [comment]
@tmarman Please accept my apologies. I didn't see this. There's example code for configuring the provider in the unit tests. I shall be writing additional documentation over the next few days.
