### ISSUE TITLE
Build failure on macOS

### ISSUE THREAD

**Issue by fhintsch** [SixLabors/ImageSharp.Web#53]
### Prerequisites
Install ImageSharp.Web-master on a Mac. Start _Visual Studio_  with `ImageSharp.Web.sln`
### Description
Building _ImageSharp.Web_ does not produce a target _netstandard2.0_ as wanted by
corresponding line 7 in *.csproj:
`<TargetFrameworks>netstandard1.4;netstandard2.0</TargetFrameworks>`

Only target _netstandard1.4_ is built.

That leads to an error when building ImageSharp.Web.Sample application. This application refers to  netstandard2.0 target.

Changing line 7 in *.csproj:
`<TargetFrameworks>netstandard2.0</TargetFrameworks>`
solves the problem.

(same problem in `ImageSharp.Web.Test.csproj`)

### System Configuration

- ImageSharp.Web version: 1.0.0-beta6 
- Other SixLabors packages and versions:
- Environment (Operating system, version and so on): macOS 10.14.2
- .NET Core version: 2.1.2
- Additional information: VS Community for Mac 7.7.3

**Comment by James-Jackson-South** [comment]
Interesting. Our solution builds fine and unit tests run fine on Linux 

That’s not really a solution you’ve described as we need the multiple targets and our usage is as described in the MS documentation. Are you sure you do not have an issue with your installation?

**Comment by JimBobSquarePants** [comment]
I think your issue is due to a missing 1.X NETCore SDK on your machine. 

https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support

**Comment by fhintsch** [comment]
Indeed, that’s only a workaround.

I will try with linux.

**Comment by fhintsch** [comment]
My main problem is #55!

(I’m developing on a Mac and deploying for a linux based docker container)

**Comment by fhintsch** [comment]
Complete dotnet reinstall solved my problem, see #55
