### ISSUE TITLE
AzureBlobStorageImageProvider extremely poor performance

### ISSUE THREAD

**Issue by fergalmoran** [SixLabors/ImageSharp.Web#60]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp.Web
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp.Web/issues) and [closed](https://github.com/SixLabors/ImageSharp.Web/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Using the new AzureBlobStorageImageProvider is extremely slow.

### Steps to Reproduce

```
            services.AddImageSharpCore ()
                .SetRequestParser<QueryCollectionRequestParser> ()
                .Configure<PhysicalFileSystemCacheOptions> (options => {
                    options.CacheFolder = "/tmp/pn-cache";
                })
                .SetCache<PhysicalFileSystemCache> ()
                .SetCacheHash<CacheHash> ()
                .AddProvider<AzureBlobStorageImageProvider> (AzureProviderFactory)
                .Configure<AzureBlobStorageImageProviderOptions> (options => {
                    options.ConnectionString = connectionString;
                    options.ContainerName = containerName;
                })
                .AddProcessor<ResizeWebProcessor> ();
```
where AzureProviderFactory is
```        
private static AzureBlobStorageImageProvider AzureProviderFactory (IServiceProvider provider) {
            var containerName = provider.GetRequiredService<IOptions<ImageFileStorageSettings>> ().Value.ContainerName;

            return new AzureBlobStorageImageProvider (
                provider.GetRequiredService<IOptions<AzureBlobStorageImageProviderOptions>> (),
                provider.GetRequiredService<FormatUtilities> ()) {
                Match = context => {
                    return context.Request.Path.StartsWithSegments ($"/{containerName}");
                }
            };
        }
```
### System Configuration

Ubuntu 19.04 and CoreOS running docker and Kubernetes in Azure Container Service.
- ImageSharp.Web version: latest
- Other SixLabors packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

I believe the issue is that ImageSharpMiddleware calls
```
IImageResolver sourceImageResolver = await provider.GetAsync(context).ConfigureAwait(false);
```

before checking the cache and in the case of the AzureBlobStorageImageProvider this causes a CloudBlockBlob to be instantiated and ExistsAsync() to be called. This kills performance especially when many images are being loaded at once.

On the other hand, I might just be doing it all wrong..

**Comment by JimBobSquarePants** [comment]
How slow is "Extremely poor performance"?

`ExistsAsync()` is just a wrapper around a http request (it should just be a head one, I haven't checked) that returns false if it encounters a 404 response. The size of the source image should not be relevant at this point. 

You can see it here.

https://github.com/Azure/azure-storage-net/blob/07d66a4917ab03cb5e7262774235d2d2f7e65752/Lib/ClassLibraryCommon/Blob/CloudBlob.cs#L3607

Performance, of course, when working with http requests is limited by connection speeds and latency. I'm assuming all your resources are in the same geographic region?

**Comment by fergalmoran** [comment]
Slow enough for ya? 😸 
![image](https://user-images.githubusercontent.com/309139/59619846-55bf6400-9123-11e9-8d01-7e78662e1161.png)
(ignore the ngsw-bypass - was just making sure it wasn't a weird service worker interaction)

Everything is in the same region (Europe North) - I'm certain this isn't a resources/bandwidth issue. I'm unconvinced by my original theory now but I had to move onto something else but I'll keep investigating and get back to you.

This only happens if I request multiple images at the same time, single images are always millisecond response so I think it might be a lock issue? I'm getting more familiar with the codebase and hope to have some more time at the weekend to look into it further. Sorry to be so vague for now.

**Comment by fergalmoran** [comment]
Okay, my bad. It was cache-missing due to me caching my images outside the wwwroot folder. All good now..

**Comment by JimBobSquarePants** [comment]
@fergalmoran Ah yeah, you can't do that with the default file system cache. There's no file watchers like in old MVC so no performance implications to storing images in wwwroot.
