### ISSUE TITLE
RemoveProvider Builder Extensions don't work

### ISSUE THREAD

**Issue by deanmarcussen** [SixLabors/ImageSharp.Web#62]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp.Web (Yes this time!)
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp.Web/issues) and [closed](https://github.com/SixLabors/ImageSharp.Web/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The `ImageSharpCoreBuilderExtensions.RemoveProvider<TProvider>` helper extensions don't work.

### Steps to Reproduce
Call `.RemoveProvider` and then check the Service Collection afterwards.

### Fix
The ServiceCollection is an `ICollection` so `Remove` needs to find the instance that exists of the `ServiceDescriptor` rather than a new instance created by `ServiceDescriptor.Singleton<IImageProvider, TProvider>()`

Example (from the `ServiceCollectionDescriptorExtensions.Replace` method)
```
            var registeredServiceDescriptor = collection.FirstOrDefault(s => s.ServiceType == descriptor.ServiceType);
            if (registeredServiceDescriptor != null)
            {
                collection.Remove(registeredServiceDescriptor);
            }
```

Implementation factories are different again, as it doesn't register the `TImplementationType` when creating a `ServiceDescriptor` so you need to examine the factory return type
```
            var registeredServiceDescriptor = services.FirstOrDefault(x => 
                x.ServiceType == typeof(IImageProvider) && 
                x.Lifetime == ServiceLifetime.Singleton &&
                x.ImplementationFactory.Method.ReturnType == typeof(TProvider));
            if (registeredServiceDescriptor != null)
            {
                collection.Remove(registeredServiceDescriptor);
            }
```

**Comment by JimBobSquarePants** [comment]
Hey @deanmarcussen thanks for the issue and the fix! I'll get it implemented asap
