### ISSUE TITLE
UnauthorizedAccessException on Web Server

### ISSUE THREAD

**Issue by chadlevn** [SixLabors/ImageSharp.Web#65]
### Description
UnauthorizedAccessException when accessing images on web server. Works locally.

```
UnauthorizedAccessException: Access to the path '~path~\wwwroot\is-cache\2\8\b\3\8\7\f\6\8\b\0\8' is denied.

    System.IO.__Error.WinIOError(int errorCode, string maybeFullPath)
    System.IO.Directory.InternalCreateDirectory(string fullPath, string path, object dirSecurityObj, bool checkHost)
    System.IO.Directory.InternalCreateDirectoryHelper(string path, bool checkHost)
    System.IO.Directory.CreateDirectory(string path)
    SixLabors.ImageSharp.Web.Caching.PhysicalFileSystemCache.SetAsync(string key, Stream stream, ImageMetaData metadata)
    SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
    Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
    Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Steps to Reproduce
Configuration for `startup.cs` class.
`ConfigureServices` method:
```
services.AddImageSharp();
```

`Configure` method:
```
app.UseImageSharp();
app.UseStaticFiles();
```

### System Configuration
ImageSharp.Web v1.0.0-beta0007
Windows Server 2012 R2
.NET Framework version: 4.7.2
AspNetCore v2.2.0

**Comment by JimBobSquarePants** [comment]
It’s not an error from accessing cache but an error creating a directory to store the cached item. Looks to me like a configuration issue on your server. You’ll need to assign write permissions to the root

**Comment by chadlevn** [comment]
> 
> 
> It’s not an error from accessing cache but an error creating a directory to store the cached item. Looks to me like a configuration issue on your server. You’ll need to assign write permissions to the root

Ah yes. That was exactly it. I gave write permission to our network service and it is working. Thanks!
