### ISSUE TITLE
BlobStorageImageProvider won't work anymore without query parameters

### ISSUE THREAD

**Issue by wagich** [SixLabors/ImageSharp.Web#77]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp.Web
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp.Web/issues) and [closed](https://github.com/SixLabors/ImageSharp.Web/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Since merging pull request #73 "Return on no commands", the `ImageSharpMiddleware` directly hands off request processing to the next middleware in the pipeline when there aren't any commands found.

This prevents any provider fetching images from a remote source (as the Azure Blob Storage Provider does) from running in a "pass-through" scenario without any transforms. Only images present on the filesystem still work, because the `StaticFileMiddleware` handles those requests.

It would be extremely unfortunate to need a second, separate middleware to handle those requests given that it would need to completely duplicate the functionality of the already present provider.

### Steps to Reproduce
- Default config with AzureBlobStorageImageProvider set as image provider
- Access image URL without any query parameters

### System Configuration
- ASP.NET Core 3.0 Preview 9
- SixLabors.ImageSharp.Web 1.0.0-dev000227

**Comment by wagich** [comment]
On second thought, there could be a config flag to turn the early-return behavior off, that would keep the (I'm assuming) common case fast but still enable the pass-through scenario for custom providers.

**Comment by JimBobSquarePants** [comment]
@wagich The system was designed originally to not process images without commands but I can see a purpose for that now with the new external image providers. A configurable switch does seem like a sensible approach 👍

**Comment by wagich** [comment]
Would you be open to a PR? I'll need to implement it anyhow in my code and would be happy to contribute.

One alternative to a config switch could also be to move the switch to the provider. Then the middleware could bail (or continue) after chosing a provider.



On Fri, Sep 13, 2019 at 4:14 PM +0200, "James Jackson-South" <notifications@github.com<mailto:notifications@github.com>> wrote:


@wagich<https://github.com/wagich> The system was designed originally to not process images without commands but I can see a purpose for that now with the new external image providers. A configurable switch does seem like a sensible approach 👍

**Comment by andymac4182** [comment]
This would be great! We ended up implementing our own middleware that just returned the raw image.

**Comment by JimBobSquarePants** [comment]
This has now been fixed by #83 and is available on MyGet
