### ISSUE TITLE
cache path isn't valid

### ISSUE THREAD

**Issue by yohsii** [SixLabors/ImageSharp.Web#78]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp.Web
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp.Web/issues) and [closed](https://github.com/SixLabors/ImageSharp.Web/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
ImageSharp.Web is no longer working in asp.net 3.0 (full release version). the error is:
```
ArgumentException: The path in 'value' must start with '/'. (Parameter 'value')
Microsoft.AspNetCore.Http.PathString..ctor(string value)
Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsFileProvider.StartsWithBasePath(string subpath, out PathString rest)
Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsFileProvider.GetFileInfo(string subpath)
Microsoft.Extensions.FileProviders.CompositeFileProvider.GetFileInfo(string subpath)
SixLabors.ImageSharp.Web.Caching.PhysicalFileSystemCache.GetAsync(string key)
SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.ProcessRequestAsync(HttpContext context, bool processRequest, IImageResolver sourceImageResolver, ImageContext imageContext, IDictionary<string, string> commands)
SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
the fix for this issue is straightforward, in PhysicalFileSystemCache.cs on line 75 there's a call:
```
string path = this.ToFilePath(key);
```

the bug occurs when this path doesn't start with forward slash "/". as you can see from the stack trace of the error, the path eventually gets passed to the `Microsoft.AspNetCore.Http.PathString` constructor which expects the path to start with forward slash.

**EDIT:** i initially reported that this was no longer an issue for PhysicalFileSystemProvider in the full 3.0 release but this isn't the case - it's still an issue. it was only working because of my change to ensure the path started with "/". once i got rid of my changes the issue resurfaced. of course both physical and azure provider both use the same caching mechanism and it's the PhysicalFileSystemCache that's causing the issue.

### Steps to Reproduce
i'd link you to my project but you'd have to setup so many things to get it running it might be easier to just create a new asp.net 3.0 project and try to resize an image.

### System Configuration

- ImageSharp.Web version: 1.0.0-beta0009
- Other SixLabors packages and versions:
imagesharp 1.0.0-beta0007
imagesharp.drawing 1.0.0-beta0007
imagesharp.web.providers.azure 1.0.0-beta0009
- Environment (Operating system, version and so on):
windows 10
- .NET Framework version:
.net core 3.0
- Additional information:

**Comment by JimBobSquarePants** [comment]
Interestingly no changes to `PathString` in 4 years!

https://twitter.com/ben_a_adams/status/1178897720804876289
https://github.com/aspnet/AspNetCore/blame/master/src/Http/Http.Abstractions/src/PathString.cs

![Git blame PathString](https://pbs.twimg.com/media/EFxJOmWWsAEqbMt?format=png&name=small)

**Comment by deanmarcussen** [comment]
Core 3 is working fine for us

Is it possible you have changed the WebRootFileProvider to a composite?

```
Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsFileProvider.StartsWithBasePath(string subpath, out PathString rest)
Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsFileProvider.GetFileInfo(string subpath)
Microsoft.Extensions.FileProviders.CompositeFileProvider.GetFileInfo(string subpath)
```

The default wwwroot file provider (even on core3) is a physical file provider which doesn't use `PathString` but in your stack trace I'm seeing a composite which is using a `StaticWebAssetsFileProvider`, which is a new one to me, and seems to be using `PathString`

**Comment by yohsii** [comment]
@deanmarcussen thanks for the info. it's really interesting that composite file provider seems to be the default in my project. i wonder why - i haven't set it explicitly anywhere.

anyway, if i specify the file provider to be PhysicalFileProvider like you suggested in my PhysicalProviderFactory like so:
```
PhysicalFileSystemProvider PhysicalProviderFactory(IServiceProvider provider)
            {
                var env = provider.GetRequiredService<IHostingEnvironment>();
                env.WebRootFileProvider = new PhysicalFileProvider(env.WebRootPath);
                var p = new PhysicalFileSystemProvider(
                    env,
                    provider.GetRequiredService<FormatUtilities>())
                {
                    Match = context =>
                    {
                        return context.Request.Path.StartsWithSegments("/media");
                    }
                };

                return p;
            }
```
it works without the change in #79 

but i reckon ImageSharp.Web should take care of this detail for you because if you look at the constructor of `PhysicalFileSystemProvider`:
```
public PhysicalFileSystemProvider(
            IHostingEnvironment environment,
            FormatUtilities formatUtilities)
        {
            Guard.NotNull(environment, nameof(environment));

            this.fileProvider = environment.WebRootFileProvider;
            this.formatUtilities = formatUtilities;
        }
```
it sets the file provider to be the WebRootFileProvider of the environment that's passed in. if it doesn't support CompositeFileProvider it should actually set file provider to explicitly use PhysicalFileProvider like so:
```
this.fileProvider = new PhysicalFileProvider(environment.WebRootPath);
```

otherwise it will set the fileProvider to be something that is potentially unsupported. this will trip up others who are inadvertently using CompositeFileProvider.

**Comment by JimBobSquarePants** [comment]
> but i reckon ImageSharp.Web should take care of this detail for you because if you look at the constructor of PhysicalFileSystemProvider:

It works with the default provider so I'm not convinced we should make that change. You must have code in your solution setup that deviates from the default.

**Comment by JimBobSquarePants** [comment]
Thinking about it more and explicitly setting the provider is probably wise. Good thinking!

**Comment by deanmarcussen** [comment]
So this just made me curious to find out what a StaticWebAssetsFileProvider is, so I had a look around the core3 codebase.

It's added by default by WebHostBuilder, but only in Development

https://github.com/aspnet/AspNetCore/blob/f726cb47c8e1ae5474c270496fc603fdf984f167/src/Hosting/Hosting/src/StaticWebAssets/StaticWebAssetsFileProvider.cs#L12-L25

It does seem to preclude the idea that you might want to write to the webroot file provider, which I find a bit strange.

Creating a new PhysicalFileProvider from the env.webroot should probably work ok - it's something I've done, but reluctantly, not knowing if there will be an edge case where it causes other problems

**Comment by JimBobSquarePants** [comment]
Bonkers. Why would it only do it during development?

**Comment by deanmarcussen** [comment]
> Bonkers. Why would it only do it during development?

Properly weird. Who approved that PR?

**Comment by yohsii** [comment]
hmm. right so it's only required during Development because in production (after a publish) the files are moved to the correct place.
this is a nice to know detail though
