### ISSUE TITLE
PNG decoding from Azure blob stream throws "ImageFormatException: Bad method for ZLIB header: cmf=251"

### ISSUE THREAD

**Issue by ColeAtRecRoom** [SixLabors/ImageSharp.Web#85]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp.Web
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp.Web/issues) and [closed](https://github.com/SixLabors/ImageSharp.Web/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
PNG decoding of 3 problematic images (included in the project) directly from an Azure blob stream throws `ImageFormatException: Bad method for ZLIB header: cmf=251`. This issue is resolved by reading the entire blob stream, copying it to a `MemoryStream`, and returning the `MemoryStream` (as seen in `CustomAzureBlobStorageImageResolver.cs`).

### Steps to Reproduce
Download project ([ImageSharp.Web.Png.DecodeExceptionRepro.zip](https://github.com/SixLabors/ImageSharp.Web/files/4099834/ImageSharp.Web.Png.DecodeExceptionRepro.zip)), create "img" container in Azure blob storage (by default the project connects to a local Azure storage emulator), upload the 3 images in the `Images` folder to blob storage, run the project & request the first image with the following URL: http://localhost:5020/img/1.png?width=512. This should result in the exception. Requesting the other 2 images should result in the exception as well.

Now, stop running the project, open `Startup.cs`, modify `ConfigureServices` to use `CustomAzureBlobStorageImageProvider` (which returns a `MemoryStream` instead of an Azure blob stream) instead of `AzureBlobStorageImageProvider`. Re-run & re-request the URL. It should work.

The `Custom...` classes are based on code in master branch of this repo, with slight modifications marked by `// CHANGED` comments.

The .png files are valid according to pngcheck.

### System Configuration
- **ImageSharp.Web version:** v1.0.0-beta0009
- **Other ImageSharp packages and versions:** SixLabors.ImageSharp.Web.Providers.Azure v1.0.0-beta0009
- **Environment (Operating system, version and so on):** Windows 10 Home 64-bit (10.0, Build 18362)
- **.NET Framework version:** .NET Core 3.1
- **Additional information:** Microsoft Visual Studio Professional 2019 - Version 16.4.0

**Comment by JimBobSquarePants** [comment]
Thanks for raising this @ColeShepherdAG and also thanks for providing so much useful information! 

I've seen this issue before in the ImageSharp chatrooms. It's something to do with the way Azure storage handles asynchronous streams. I remember there was one method of theirs that was causing issues intermittently but we'd avoided that so far. 

Copying the stream is a good fix. I'll create a PR soon. 👍

**Comment by danceolpan** [comment]
We had this error when uploading png files and after ImageSharp version upgrade from 1.0.0 to 2.1.9 the issue is solved. Thanks!
