### ISSUE TITLE
BackgroundColorWebProcessor does not work

### ISSUE THREAD

**Issue by OV2012** [SixLabors/ImageSharp.Web#96]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp.Web
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp.Web/issues) and [closed](https://github.com/SixLabors/ImageSharp.Web/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

The BackgroundColorWebProcessor  doesn't work.  It doesn't matter if you try to set a hex or rgb value, you will still get the same result.

### Steps to Reproduce

/imagesharp-logo.png?width=315&bgcolor=**red**

### FIX
instead of Rgba32 converter (that by the way is not registered in the CommandParser) we should use the Color Converter

```
public FormattedImage Process(FormattedImage image, ILogger logger, IDictionary<string, string> commands)
{
	//Rgba32 background = CommandParser.Instance.ParseValue<Rgba32>(commands.GetValueOrDefault(Color)); 
	Color background = CommandParser.Instance.ParseValue<Color>(commands.GetValueOrDefault(Color));
	if (background != default)
	{
		image.Image.Mutate(x => x.BackgroundColor(background));
	}

	return image;
}
```

### System Configuration

- ImageSharp.Web version: 1.0.0-rc0001
- Other ImageSharp packages and versions: SixLabors.ImageSharp.Web.Providers.Azure (1.0.0-rc0002)
- Environment (Operating system, version and so on): Win10 x64 Prof
- .NET Framework version: netcoreapp 3.1
- Additional information: VS2019

**Comment by JimBobSquarePants** [comment]
Thanks for raising this with so much detail, we really appreciate that! 

I've just merged a fix into the master branch which will trigger a build on our MyGet  nightlies. You can get download the updated package from the link in our readme once the build is complete.

**Comment by OV2012** [comment]
perfect! and thank you too for the quick reaction!!
